//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusMetal_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptedOffer
    {
        public int OfferId { get; set; }
        public int StaffId { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Note { get; set; }
    }
}
