//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusMetal_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOutput
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Count { get; set; }
        public string Explanation { get; set; }
    }
}
