//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusMetal_Pro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PegasusYazilimEntities : DbContext
    {
        public PegasusYazilimEntities()
            : base("name=PegasusYazilimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcceptedOffer> AcceptedOffer { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<InOutput> InOutput { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Offer> Offer { get; set; }
        public virtual DbSet<Piece> Piece { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectContinuing> ProjectContinuing { get; set; }
        public virtual DbSet<ProjectFiles> ProjectFiles { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<StockCategory> StockCategory { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
