//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusMetal_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Quality { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> WasteRate { get; set; }
    }
}
