//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusMetal_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Property { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> HourPrice { get; set; }
        public Nullable<decimal> MinutePrice { get; set; }
    }
}
